### ISSUE TITLE
EAN13 - wrong value encoded in bars

### ISSUE THREAD

**Issue by piotr-rusol** [lindell/JsBarcode#116]
**Input:** 12 position with leading zeros, e.g. 000000000001
**Output** text representation 12 positions plus control sum: 0000000000017
**Value read** from bars 11 positions plus control sum: 000000000017

Encoded one position less than it supposed to be.

**Comment by lindell** [comment]
What is the symbology (barcode format) format you are using?

**Comment by lindell** [comment]
I get this result when I encode 000000000001
![0000000000017](http://bit.ly/2g9T5Ax)

Could you please explain how you get your result?

**Comment by piotr-rusol** [comment]
As in issue subject it is EAN13 by declarative way in svg.

E.g.

<svg class="barCode" style=" width: 48mm; height: 10mm; background-color:
white;margin: 0; padding: 0; " jsbarcode-format="ean13"
jsbarcode-value="000000000001" jsbarcode-textmargin="0"
jsbarcode-marginleft="0" jsbarcode-marginright="0" jsbarcode-margintop="0"
jsbarcode-marginbottom="0" jsbarcode-height="20"></svg>



2016-12-07 11:24 GMT+01:00 Johan Lindell <notifications@github.com>:

**Comment by lindell** [comment]
I still get the same result. http://codepen.io/lindell/pen/JbvZjW

**Comment by piotr-rusol** [comment]
Yes you did and as I wrote text representation is correct. Next try to read this code by code reader and you will get 11 positions data and 1 position control sum.

**Comment by lindell** [comment]
The barcode is correctly encoded. But you reader is probably reading the barcode as an UPC barcode. UPC is the subset of EAN barcodes where it begin with a 0. If you have an EAN article number it will never start with a 0.

**Comment by piotr-rusol** [comment]
It has perfect sens as UPC was introduced in USA and Canada where codes starts from 0. When I get to office I add country code "590" at the beginning and then check if it steel occurs.

**Comment by lindell** [comment]
Have you confirmed that this was the problem?

**Comment by piotr-rusol** [comment]
I wasn't in office yet but I plan to be this evening.

**Comment by olegpidsadnyi** [comment]
Doesn't work for me. According to UPC-A codes that start with 0 have to duplicate 0 in front of them instead of the checksum.
I caught it using zxing scanner component.

**Comment by lindell** [comment]
@olegpidsadnyi I don't quite understand what you mean. Can you please link to any source of what you are talking about?

**Comment by olegpidsadnyi** [comment]
@lindell According to http://www.barcodeisland.com/ean13.phtml ean 13 has to duplicate the leading 0.
Does it mean I can't use codes looking like "075678164125"?
When I supply 12-digit code to the jsbarcode it will calculate the checksum for me.
In case of the leading zero I have to prepend another 0 and then the code is 13 digit ("0075678164125") and rendered correctly. If i supply "075678164125" the checksum 2 will be appended instead of the leading 0.

Do you think jsbarcode has to be aware of this leading 0 codes for ean13?
On the other hand I'm using pythonic package fake-factory and their function ean13 to generate codes. I think these codes that i have are not really valid. Nevertheless it is interesting if a valid UPC-A code like "075678164125" has to be rendered by jsbarcode as "0075678164125" or not.
Thanks

**Comment by lindell** [comment]
@olegpidsadnyi If I get this right, you want to generate a UPC barcode with EAN-13? That can be done by adding a 0 as you seem to understand. But it would be simpler to just use the UPC barcode format that JsBarcode provides.
