### ISSUE TITLE
Generate on other browser window

### ISSUE THREAD

**Issue by xtreemsolution** [lindell/JsBarcode#117]
Can we generate bar codes in different chrome window ? Insead we have bar code js on second window then getting no error with no bar codes .

**Comment by lindell** [comment]
I can't unfortunately not understand what you mean. Could you please describe what you want to do a bit more and add attach an example.

**Comment by piotr-rusol** [comment]
This issue is not relevant to JsBarcode nor even jQuery.

I understand and I am doing it right know :) Yes you can but because XSS secure in Chrome and other browsers you can not just simply:

newWindow = window.open("","myWindow"); and operate on document associated with this new window. 

I found it is required to open new window and write to it by old way: newWindow.document.write(); Off course in the internet are many examples to open and manipulate other window and document but only this method is 100% sure that browser do not block this.

In this way you have to use barcodes in declarative form described in README https://github.com/lindell/JsBarcode#or-define-the-value-and-options-in-the-html-element

**Comment by lindell** [comment]
I close this issue since the creator seems inactive.
