### ISSUE TITLE
No element to render on on second execution

### ISSUE THREAD

**Issue by dlusignan** [lindell/JsBarcode#139]
Hi,

Not sure if it's an issue, but when I show the barcode in a modal window ; on the first execution of the window, the barcode is there. If a press cancel and reopen the window, the render method throw No element to render on.

I can't figure why the error. Does someone have an idea ?

Thank you.

**Comment by lindell** [comment]
Most likely not a issue with JsBarcode. `No element to render on` is only thrown when a element can't be found. I can't really help you or determine if the problem lies within JsBarcode if you can't provide any example.

**Comment by dlusignan** [comment]
Look at this.

https://jsfiddle.net/u97Lh4kb/

Click on show and see the barcode. Click on cancel. Click on Show again and the error occurs.

**Comment by lindell** [comment]
The problem is that you create an svg element in the html that you then append to the box on click. When you cancel the box, you reset the html an thereby removing the element. When you click the second time the element is removed and there is therefore no element to render on.

This can be fixed by multiple way, you could move the element before resetting the box but I would recommend creating the svg element instead of moving it into the box.

https://jsfiddle.net/xxudkqc8/

**Comment by dlusignan** [comment]
That did the trick.

Thanks a lot
