### ISSUE TITLE
Barcode data without canvas

### ISSUE THREAD

**Issue by keeslinp** [lindell/JsBarcode#140]
Hey,

I have a very peculiar situation with my rendering where I need to render things without using canvas or dom elements. Is it possible to use this library to get the data (ie bitmap values or size of bars) for a given barcode? I was able to write my own for UPC-A but now there's a requirement for all of the barcode types and I'd really rather avoid rewriting a lot of what you've already accomplished.

Thanks for all your work!

EDIT: I was looking through the code, it doesn't look possible at this time. This line seems pretty clear to me, https://github.com/lindell/JsBarcode/blob/master/src/JsBarcode.js#L28

If you're alright with it I don't mind adding the feature myself. Just let me know how you'd like it to be done and I can go ahead and do that.

**Comment by lindell** [comment]
You are free to add the feature if you find a nice implementation :)

Otherwise, all barcodes are well decoupled from the rest of the implementation in 
https://github.com/lindell/JsBarcode/blob/master/src/barcodes/
For examples:
https://github.com/lindell/JsBarcode/blob/master/src/barcodes/pharmacode/index.js

Most of when return a binary string but some (for example EAN) return a little bit more complex data (not a lot). The project is under MIT so if you want to copy just those file you are free to do so as long as credit is given.

**Comment by keeslinp** [comment]
Awesome, thanks for the fast response. I was just digging through the code a little bit I think the easiest way would be to just pass an array instead of an element (this needs some tweaking cause you're already looking for an array) and then just make a renderer that draws to that array instead of an HTML element. It would probably be better to return an array rather than drawing to one but this fits your programs flow better.

Thoughts?

**Comment by lindell** [comment]
Even thou I don't think editing an array that is passed as a parameter is a super nice solution (prefer pure functions even if JsBarcode is not). I still think it is the best solution because of two reasons.
1. To have consistency between all types of renderings
2. The ['advanced use'](https://github.com/lindell/JsBarcode#more-advanced-use-case) of JsBarcode returns an object that can be used to build more advanced concatenations of barcode. The `render()` method could of course return this array but I think this should be reserved for potential other functionality.

**Comment by keeslinp** [comment]
I didn't understand what that example was doing, I didn't look there deeply enough. Thanks for pointing that out.

Would it be easier to just allow passing in a null element so that someone can grab the data without needing to render something?

here was a quick test with a dummy canvas:

``` 
jsBarcode(document.createElement('canvas'), 'test', {
    'code128',
}).options();
```

and that returned the values needed.

If you prefer to stay current I can write a quick PR where the user can pass in an object and then the options are just put on there instead of needing to call options afterwards.

**Comment by kinkoazc** [comment]
Hello. How is the option of render-to-object used further? I'm asking because I'm trying to get a dataURL of the image, without relying on the 'canvas' dependency(no available build for the arch that I use, armv7l). Don't know if this is even possible.

**Comment by SanichKotikov** [comment]
@kinkoazc there is no 'render-to-object' option. Use a 'virtual' canvas element to draw your barcode and then get dataURL from it.

**Comment by kinkoazc** [comment]
@SanichKotikov By render-to-object I meant [this](https://github.com/lindell/JsBarcode/blob/master/bin/renderers/object.js) renderer. I can't create a [virtual] canvas element, since the env is Node, and that will require the use of 'canvas'(having no build available for the arch that I use). I managed to work around this problem by replacing 'canvas' with a SVG element, created using jsdom. Something like this:
`
            const jsdom = require('jsdom');
            const { JSDOM } = jsdom;

            const { document } = (new JSDOM('<svg></svg>')).window;
            JsBarcode(document.querySelector('svg'), barcode, {
                format: 'CODE39',
                ...
                xmlDocument: document
            });
            const svgStr = document.querySelector('svg').outerHTML;
            return svgToDataURL(svgStr);  // converting SVG to dataURL(not really recommended)
`

**Comment by SanichKotikov** [comment]
This renderer just fill-out an object with bars data.

**Comment by kinkoazc** [comment]
Yep. That's why I was wondering how I can use the info from the resulted object to generate the dataURL(if at all possible). But, problem solved :-)
Thank you for your help and quick replies!

**Comment by hernanarakaki-solu** [comment]
Hello @kinkoazc did you manage to handle that information? I'm (after 6 years) on the same situation and the Readme says `data will be filled with a encodings property which has all the needed values. See wiki for an example of what data looks like.` but there is no information about this on the wiki.

Thanks in advance

cc: @lindell
