### ISSUE TITLE
Implementation of CODE128's quiet zone

### ISSUE THREAD

**Issue by SanichKotikov** [lindell/JsBarcode#151]
Different sources told that CODE128 also has `quiet zone`, for example:

> Quiet zone: The minimum width of the Quiet Zone to the left and right of the 128 Bar Code is 10x, where x is the minimum width of a module. It is mandatory at the left and right side of the barcode. The quiet zone must not be less than 4 mm × 1.65 mm depending on the type of bar code.

![CODE128](https://upload.wikimedia.org/wikipedia/commons/8/83/Barcode_diagram.svg)

I can implement it as a part of CODE128 class. But there are some issues, for example, enable it as default (then this change affects everybody, that not good maybe) or add it as an option (not sure about this). Maybe this `quiet zone` isn't necessary?

@lindell what do you think?

Also, anybody who have any details about this issue, pls welcome into comments :)

**Comment by lindell** [comment]
This is a requirement set by most barcode symbologies. Because of this it is already possible to set the quite zone in JsBarcode with marginLeft and marginRight.

````javascript
JsBarcode("#barcode", "test", {
  background: "#f00",
  marginLeft: 10, // Default
  marginRight: 10 // Default
});
````

![image](https://cloud.githubusercontent.com/assets/284868/26124900/824d5fbe-3a80-11e7-8497-02c4fb27644b.png)


````javascript
JsBarcode("#barcode", "test", {
  background: "#f00",
  marginLeft: 30,
  marginRight: 30
});
````

![image](https://cloud.githubusercontent.com/assets/284868/26124819/2729b24a-3a80-11e7-9c4a-4b91532a0416.png)

**Comment by SanichKotikov** [comment]
I thought it's mandatory and should be even if we set margin to 0. But, it's cruel 🤣

**Comment by lindell** [comment]
It is mandatory. But someone might want to generate only the barcode and for example have a white div behind it instead.
