### ISSUE TITLE
Blurry Render at small sizes

### ISSUE THREAD

**Issue by seansean11** [lindell/JsBarcode#27]
Really appreciate the library.  I need to render barcodes at sizes below a width of '1' as set in the options.  When I use fractions such as .9 or .8, the data-uri renders very blurry.  Is there anything that can be done programmatically to ensure clarity at smaller widths?

**Comment by lindell** [comment]
That would be impossible. One line needs to be one pixel or more. If you want to understand why you could read more about computer graphics, specifically [pixels](http://en.wikipedia.org/wiki/Pixel).

**Comment by seansean11** [comment]
I didn't dig into your code in order to make comparisons, but I ended up using this older jQuery [barcode generator]https://github.com/jbdemonte/barcode library and it rendered the Code39 barcodes at a smaller width, which was perfect for the ID cards they needed to be printed on.  Thanks for the article though ;-)

**Comment by lindell** [comment]
That project is using seems to be using [Scalable Vector Graphics](http://en.wikipedia.org/wiki/Scalable_Vector_Graphics) to render the image while this project uses PNG (since the plan have always been that this project should be used at the web). One way you could get around this is to render a barcode with a wider width and then just use it but scale it down, should do the job.
