### ISSUE TITLE
Centered barcode inside fixed size canvas?

### ISSUE THREAD

**Issue by cameronelliott** [lindell/JsBarcode#359]
Hey, awesome library!

I am trying to draw centered barcodes in a canvas of a fixed size, say: 1920x1080
I have experimented with the config parameters, but it doesn't seem there isn't a straight-forward way
to get a particular sized canvas. JsBarcode will set the height/width based upon it's results.

I was almost able to get there by using margins, but it's not straightforward to compute the font width, etc.
I suppose I could render each image twice, and use the results from the first render to algebraically solve
for the margin numbers I need to get a 1920x1080 canvas, but that's a bit rough, and I am in 
a performance sensitive application.

Any suggestions on how to get the barcode rendered into a pre-sized canvas without resizing?

Thanks
Cameron

**Comment by lindell** [comment]
JsBarcode does not support fixed with fixed margins since that would require squashing of pixels and make the barcode unreadable.

What you could do it follow this: https://stackoverflow.com/questions/11625767/canvas-inside-canvas-of-html5

Generate a barcode that you know will fit in the 1920 width. Then center that in the 1920x1080 canvas.
