### ISSUE TITLE
How to get DataURI from generated barcode???

### ISSUE THREAD

**Issue by yilunc** [lindell/JsBarcode#370]
I need the data URI from the generated barcodes but i can't use `canvas` because it doesn't work with firestore cloud functions. Theres clearly no easy way to do it with svg either. How is this not a basic feature of this library? Sadly i'm not fluent enough in this library to actually understand whats going on...

**Comment by lindell** [comment]
> How is this not a basic feature of this library?

Please be aware that people working on open source projects are doing it completely in their free time. When you are acting entitled, you are very much fulfilling the "Karen" stereotype, but instead of doing it to someone working minimum wage, you are doing it to people that try to provide a service completely for free.

----

As you stated, the supported way to do this is with the `canvas` library. I'm sorry if firebase does not support it, but this library needs some way to draw its images, and writing a complete rendering engine with included png support from scratch is not something that has been done yet. But with your engagement and a few thousand hours of your work, I will happily accept the PR you will provide to help out the community! 🥰

**Comment by yilunc** [comment]
I'm sorry you automatically assumed an entitled tone from me but thats the not the case. Anyways, thanks for explaining
