### ISSUE TITLE
err:Module CODE128 does not exist or is not loaded.

### ISSUE THREAD

**Issue by loveitdoit** [lindell/JsBarcode#46]
hi, I'm depending on your steps to run the client get an error like this：
Module CODE128 does not exist or is not loaded.

How do I resolve?

**Comment by lindell** [comment]
I can't help you if you don't give me any information of how you use the library, what browser you are running on and so on. Did you use the [download page](http://lindell.me/JsBarcode/download/) to download JsBarcode?

**Comment by loveitdoit** [comment]
I'm using a Google browser, runs on windows7 system. Full access to all types according to the download page you provide. And the code is based on the step you provide

like this:

script src=jquery...
script src=jsbarcode...

script
   $(function(){
           $("#barcode").JsBarcode("9780199532179",{format:"EAN", displayValue:true, fontSize:20}); 
    });
script


img id='barcode' ...

**Comment by lindell** [comment]
"Did you use the [download page](http://lindell.me/JsBarcode/download/) to download JsBarcode?" Or did you just download the JsBarcode.js file?

**Comment by ibmjm** [comment]
Having the same problem.  Used your download page to get a minified .js file which I'm including in my page (along with jQuery) using script tags `(<script src="/my/path/to/JsBarcode.all.min.js"></script>)`.

**Comment by loveitdoit** [comment]
@ibmjm Yes, because I speak Chinese, translated by Google may not complete. Your description is correct, we have encountered the same problem

**Comment by marcokam** [comment]
@lindell I think the issue is with the registering of your individual barcode scripts.  If you run the current version of your example/index.html page you will see the error that @loveitdoit and @ibmjm are talking about.  

In CODE128.js, you have the line:
`try{register(JsBarcode)} catch(e){}`

This is failing because JsBarcode is not defined globally (it is defined in an anonymous function and never exported globally).  This seemed to have been removed in commit 09b7db2.  I'm guessing you meant to either register it as a jQuery plugin if available or as a global object otherwise?

**Comment by lindell** [comment]
Thanks @marcokam. I probably just wanted to re-arrange the code and forgot to re-add that part when cutting out the text.

The code should work again now. Could someone confirm?

**Comment by ibmjm** [comment]
Confirmed, working now.  Thanks for the timely update!
