### ISSUE TITLE
Side margins?

### ISSUE THREAD

**Issue by justrag** [lindell/JsBarcode#51]
What's the option to use to eliminate the margin on the left and right side of the barcode? Neither {margin:0} nor {marginLeft:0,marginRight:0} seem to work.

Also, is it possible to specify the width of the resulting image?

**Comment by lindell** [comment]
"quite" is the option. I have realized that it is a stupid name for that option so the next version have it renamed to [margin](https://github.com/lindell/JsBarcode/blob/master/JsBarcode.js#L273).

You can't unfortunately not set the absolute width since that would make some lines not exact pixels and make the whole barcode blurry.

**Comment by lindell** [comment]
Can also add that the idea was to name the option "quiet" but I misspelled it :P

**Comment by lindell** [comment]
I did now create a release. So if you redownload margins should work :)

**Comment by justrag** [comment]
It's indeed working now. Thanks!
